[project]
name = "khuda-ai-engineering"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "김재형", email = "jaehk28@khu.ac.kr" }
]
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.142.2",
    "python-multipart>=0.0.32",
    "sqlalchemy>=2.1.1",
    "uvicorn>=0.54.0",
]

[project.scripts]
khuda-ai-engineering = "khuda_ai_engineering:main"

[build-system]
requires = ["uv_build>=0.12.11,<0.13.0"]
build-backend = "uv_build"
